### ISSUE TITLE
Handling environment variable

### ISSUE THREAD

**Issue by rakati** [rakati/simple_shell#3]
Before implementing the commands below, we need to implement a data structure for env variables, in my opinion, a linked list with `key`, and `value` is enough, as in the assignment we are not required to create an efficient data structure (like a dictionary, binary or red-black tree).

The commands to implement are:
- [ ] `env` built-in (here env prints the current environment, we don't have to handle `env` with args).
- [ ] the `setenv` builtin:
    - Initialize a new environment variable, or modify an existing one
    - Command syntax: setenv VARIABLE VALUE
    - Should print something on stderr on failure
- [ ] the `unsetenv` builtin:
    - Remove an environment variable
    - Command syntax: `unsetenv` VARIABLE
    - Should print something on stderr on failure.
 
To translate these into code we have to implement:
- a linked list data structure with key and value (of course next ptr).
- Print list function.
- Pop from the list.
- Add Node to the list (simple: add at the end).
- re-initialize the list using the (`envp` variable passed through main args).

**Comment by amine-zzr** [comment]
i will write 3 functions or may be 4, `env, setenv for new environment variable, setenv for existing environment variable, unsetenv` am i right?

**Comment by amine-zzr** [comment]
i will write 4 or 5 functions, to handle the printing of list nodes, popping from the list adding nodes to the list and initializing the list using the `envp[]`
